### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by JohnG0024** [Xharlie/ShapenetRender_more_variation#6]
Hello, I have a few questions:

1. > you need to change render_blender.py's random range since some model always get out of the field of view

So we should change random range case by case? Is it because models from v1, v2 are all centered with almost the same size at the same location that we don't need to change the random range for them?

2. What are the `distance ratio` and `max real distance` in the `rendering_metadata.txt` file? I don't find such properties in Blender.

**Comment by ShawnXie1999** [comment]
Hello， @JohnG0024 .
   DId you change the random range when you genderate 2D Image for shapenet v2?
